"""Initial migration

Revision ID: 03fb815c289f
Revises: 
Create Date: 2023-12-14 16:33:35.794509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fb815c289f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('energy_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zip_code'], ['address.zip_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=True),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolled_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_location_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['device_model.id'], ),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['enrolled_device.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['event_label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_data')
    op.drop_table('enrolled_device')
    op.drop_table('service_location')
    op.drop_table('energy_price')
    op.drop_table('user')
    op.drop_table('event_label')
    op.drop_table('device_model')
    op.drop_table('address')
    # ### end Alembic commands ###
